### ISSUE TITLE
Enable/Disable Helix commands throw error

### ISSUE THREAD

**Issue by chapmandu** [jasonwilliams/vscode-helix#13] opened 2024-01-17 23:56 UTC
- Open VSCode command pallete
- Select either "Enable Helix" or "Disable Helix"
- Error is thrown

![image](https://github.com/jasonwilliams/vscode-helix/assets/1092563/20f6f033-0657-47ce-b5b4-ec65f03be230)

![image](https://github.com/jasonwilliams/vscode-helix/assets/1092563/30877164-fe47-406b-8849-bf4f27d248e6)

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-14-generic

Helix For VS Code
v0.5.5

**Comment by jasonwilliams** [comment] 2024-01-23 22:42
Weird, I can't reproduce this, is this happening on other platforms?

**Comment by chapmandu** [comment] 2024-01-24 10:26
No worries mate, I can still enable & disable from the extensions menu. I only have a Linux OS to test with though.

**Comment by jasonwilliams** [comment] 2024-01-29 23:34
@chapmandu try https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.6.0 it may be fixed in this release

**Comment by chapmandu** [comment] 2024-01-31 01:55
Same error is thrown. But again, not a show-stopper.

**Closed** 2024-01-31 03:45 UTC
